name: Update Spec Version

on:
  schedule:
    # Runs every Monday at midnight UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Allows manual triggering

# Grant the workflow permissions to push commits
permissions:
  contents: write

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout local repository
        uses: actions/checkout@v4

      # Step 2: Run the updater action
      - name: Check for updates and update spec file
        uses: apicalshark/rpm-spec-version-updater@main
        with:
          target-repo: 'linuxmint/webapp-manager'
          spec-file: 'webapp-manager.spec'
          tag-prefix: ''
